import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

const cabinet = localFont({
  src: [
    { path: './fonts/cabinet-grotesk/CabinetGrotesk-Regular.woff2', weight: '400' },
    { path: './fonts/cabinet-grotesk/CabinetGrotesk-Medium.woff2', weight: '500' },
    { path: './fonts/cabinet-grotesk/CabinetGrotesk-Bold.woff2', weight: '700' },
    { path: './fonts/cabinet-grotesk/CabinetGrotesk-Extrabold.woff2', weight: '800' },
    { path: './fonts/cabinet-grotesk/CabinetGrotesk-Black.woff2', weight: '900' },
  ],
  variable: '--font-cabinet',
  display: 'swap',
});

const satoshi = localFont({
  src: [
    { path: './fonts/satoshi/Satoshi-Light.woff2', weight: '300', style: 'normal' },
    { path: './fonts/satoshi/Satoshi-Regular.woff2', weight: '400', style: 'normal' },
    { path: './fonts/satoshi/Satoshi-Medium.woff2', weight: '500', style: 'normal' },
    { path: './fonts/satoshi/Satoshi-Bold.woff2', weight: '700', style: 'normal' },
    { path: './fonts/satoshi/Satoshi-Black.woff2', weight: '900', style: 'normal' },
  ],
  variable: '--font-satoshi',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "What about me?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinet.variable} ${satoshi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
